# (01/09/20) Original list of variables to use. Note that this list has redundant vars that won't be used at all (e.g. id, sec_ secondary bureau vars etc.), but it's basically the list of vars that are both in old data (up to 2018) and in data to score in 2020+

print("Loading lists of vars and printing out some list sizes...")

cols_to_use_round1 = ['id', 'member_id', 'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'acc_now_delinq', 'acc_open_past_24mths', 'bc_open_to_buy', 'percent_bc_gt_75', 'bc_util', 'dti', 'delinq_2yrs', 'delinq_amnt', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'mths_since_recent_bc', 'mort_acc', 'open_acc', 'pub_rec', 'total_bal_ex_mort', 'revol_bal', 'revol_util', 'total_bc_limit', 'total_acc', 'total_il_high_credit_limit', 'num_rev_accts', 'mths_since_recent_bc_dlq', 'initial_list_status', 'pub_rec_bankruptcies', 'num_accts_ever_120_pd', 'chargeoff_within_12_mths', 'collections_12_mths_ex_med', 'tax_liens', 'mths_since_last_major_derog', 'num_sats', 'num_tl_op_past_12m', 'mo_sin_rcnt_tl', 'tot_hi_cred_lim', 'tot_cur_bal', 'avg_cur_bal', 'num_bc_tl', 'num_actv_bc_tl', 'num_bc_sats', 'pct_tl_nvr_dlq', 'num_tl_90g_dpd_24m', 'num_tl_30dpd', 'num_tl_120dpd_2m', 'num_il_tl', 'mo_sin_old_il_acct', 'num_actv_rev_tl', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'total_rev_hi_lim', 'num_rev_tl_bal_gt_0', 'num_op_rev_tl', 'tot_coll_amt', 'application_type', 'disbursement_method', 'annual_inc_joint', 'dti_joint', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog']
print(len(cols_to_use_round1))

# Keep after all the feature engineering:
cols_to_use_post_feature_eng = ['loan_amnt',
'int_rate',
'installment',
'annual_inc',
'acc_now_delinq',
'acc_open_past_24mths',
'bc_open_to_buy',
'percent_bc_gt_75',
'bc_util',
'dti',
'delinq_2yrs',
'delinq_amnt',
'fico_range_low',
'fico_range_high',
'inq_last_6mths',
'mths_since_last_delinq',
'mths_since_last_record',
'mths_since_recent_inq',
'mths_since_recent_revol_delinq',
'mths_since_recent_bc',
'mort_acc',
'open_acc',
'pub_rec',
'total_bal_ex_mort',
'revol_bal',
'revol_util',
'total_bc_limit',
'total_acc',
'total_il_high_credit_limit',
'num_rev_accts',
'mths_since_recent_bc_dlq',
'pub_rec_bankruptcies',
'num_accts_ever_120_pd',
'chargeoff_within_12_mths',
'collections_12_mths_ex_med',
'tax_liens',
'mths_since_last_major_derog',
'num_sats',
'num_tl_op_past_12m',
'mo_sin_rcnt_tl',
'tot_hi_cred_lim',
'tot_cur_bal',
'avg_cur_bal',
'num_bc_tl',
'num_actv_bc_tl',
'num_bc_sats',
'pct_tl_nvr_dlq',
'num_tl_90g_dpd_24m',
'num_tl_30dpd',
'num_tl_120dpd_2m',
'num_il_tl',
'mo_sin_old_il_acct',
'num_actv_rev_tl',
'mo_sin_old_rev_tl_op',
'mo_sin_rcnt_rev_tl_op',
'total_rev_hi_lim',
'num_rev_tl_bal_gt_0',
'num_op_rev_tl',
'tot_coll_amt',
'annual_inc_joint',
'dti_joint',
'open_acc_6m',
'open_act_il',
'open_il_12m',
'open_il_24m',
'mths_since_rcnt_il',
'total_bal_il',
'il_util',
'open_rv_12m',
'open_rv_24m',
'max_bal_bc',
'all_util',
'inq_fi',
'total_cu_tl',
'inq_last_12m',
'Default_flag',
'highRiskZip',
'major_derog_NA',
'bc_dlq_NA',
'revol_delinq_NA',
'term_ 36 months',
'grade_A',
'grade_B',
'grade_C',
'grade_D',
'emp_length_1 year',
'emp_length_10+ years',
'emp_length_2 years',
'emp_length_3 years',
'emp_length_4 years',
'emp_length_5 years',
'emp_length_6 years',
'emp_length_7 years',
'emp_length_8 years',
'emp_length_9 years',
'emp_length_Less 1 year',
'home_ownership_MORTGAGE',
'home_ownership_OWN',
'home_ownership_RENT',
'verification_status_Source Verified',
'verification_status_Verified',
'purpose_car',
'purpose_credit_card',
'purpose_debt_consolidation',
'purpose_educational',
'purpose_home_improvement',
'purpose_house',
'purpose_major_purchase',
'purpose_medical',
'purpose_moving',
'purpose_renewable_energy',
'purpose_small_business',
'purpose_vacation',
'purpose_wedding',
'initial_list_status_f',
'application_type_Individual',
'disbursement_method_Cash']

# List of raw variables that are categorical that will be used for model later
cat_vars_raw_4_model = ['term', 'grade', 'emp_length', 'home_ownership', 
            'verification_status', 'purpose', 'initial_list_status', 
            'application_type', 'disbursement_method']

# List of continuous variables in model (same name before and after processing)
continuous_cols_4_model = ['loan_amnt',
 'int_rate',
 'installment',
 'annual_inc',
 'acc_now_delinq',
 'acc_open_past_24mths',
 'bc_open_to_buy',
 'percent_bc_gt_75',
 'bc_util',
 'dti',
 'delinq_2yrs',
 'delinq_amnt',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'mths_since_recent_bc',
 'mort_acc',
 'open_acc',
 'pub_rec',
 'total_bal_ex_mort',
 'revol_bal',
 'revol_util',
 'total_bc_limit',
 'total_acc',
 'total_il_high_credit_limit',
 'num_rev_accts',
 'mths_since_recent_bc_dlq',
 'pub_rec_bankruptcies',
 'num_accts_ever_120_pd',
 'chargeoff_within_12_mths',
 'collections_12_mths_ex_med',
 'tax_liens',
 'mths_since_last_major_derog',
 'num_sats',
 'num_tl_op_past_12m',
 'mo_sin_rcnt_tl',
 'tot_hi_cred_lim',
 'tot_cur_bal',
 'avg_cur_bal',
 'num_bc_tl',
 'num_actv_bc_tl',
 'num_bc_sats',
 'pct_tl_nvr_dlq',
 'num_tl_90g_dpd_24m',
 'num_tl_30dpd',
 'num_tl_120dpd_2m',
 'num_il_tl',
 'mo_sin_old_il_acct',
 'num_actv_rev_tl',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'total_rev_hi_lim',
 'num_rev_tl_bal_gt_0',
 'num_op_rev_tl',
 'tot_coll_amt',
 'annual_inc_joint',
 'dti_joint',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m']
print(len(continuous_cols_4_model))

# (!!) (01/09/20) Hailey dropped the below early on before feature engineering
# TODO: Might review later if any is useful, but they have LOW INFO (lots of 0s bc secondary)
cols_to_drop = ['id','member_id','funded_amnt','url','desc','title','addr_state','revol_bal_joint',
                  'sec_app_fico_range_low','sec_app_fico_range_high','sec_app_earliest_cr_line',
                  'sec_app_inq_last_6mths','sec_app_mort_acc','sec_app_open_acc','sec_app_revol_util',
                  'sec_app_open_act_il','sec_app_num_rev_accts','sec_app_chargeoff_within_12_mths',
                  'sec_app_collections_12_mths_ex_med','sec_app_mths_since_last_major_derog','zip_code','sub_grade',
                  'earliest_cr_line','emp_title','zip3digit']

# Just Hailey's list in dat processing - for reference only
cat_var_to_drop = ['term_ 60 months','grade_G','home_ownership_ANY','emp_length_nan',
                      'verification_status_Not Verified','purpose_other','initial_list_status_w',
                      'disbursement_method_DirectPay','application_type_Joint App']

# (01/09/20) Below list is for later reference/ review (cannot train with those)
new_vars_not_in_training = ['exp_default_rate',
 'service_fee_rate',
 'accept_d',
 'exp_d',
 'list_d',
 'credit_pull_d',
 'review_status_d',
 'review_status',
 'msa',
 'ils_exp_d',
 'effective_int_rate',
 'verified_status_joint',
 'mtg_payment',
 'housing_payment']